{{- $image := printf "%s:%s" .Values.backend.image.repository (.Values.backend.image.tag | default .Chart.AppVersion) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "p3m.fullname" . }}-backend
  labels:
    {{- include "p3m.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "p3m.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      {{- with .Values.backend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "p3m.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      {{- with .Values.backend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "p3m.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.backend.podSecurityContext | nindent 8 }}
      volumes:
        - name: p3m-statics
          persistentVolumeClaim:
            claimName: {{ include "p3m.fullname" . }}-statics
        - name: p3m-secrets
          secret:
            secretName: {{ include "p3m.fullname" . }}-secret
        - name: uwsgi-conf
          configMap:
            name: {{ include "p3m.fullname" . }}-uwsgi      
      initContainers:
        - name: check-if-db-is-ready
          image: "{{ $image }}"
          command: 
            - /usr/src/app/venv/bin/python
          args:
            - manage.py
            - check
          volumeMounts:
            - name: p3m-statics
              mountPath: {{ .Values.config.static.localPath }}
            - name: p3m-secrets
              mountPath: /run/secrets/p3m
          envFrom:
            - configMapRef:
                name: {{ include "p3m.fullname" . }}-env
        {{- if .Values.config.loadFixtures }}
        - name: load-fixtures
          image: "{{ $image }}"
          args:
            - echo
            - "ok"
          volumeMounts:
            - name: p3m-statics
              mountPath: {{ .Values.config.static.localPath }}
            - name: p3m-secrets
              mountPath: /run/secrets/p3m
          envFrom:
            - configMapRef:
                name: {{ include "p3m.fullname" . }}-env
          env:
            - name: LOAD_FIXTURES
              value: 'true'
        {{- end }}
      {{- with .Values.backend.extraHosts }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-backend
          securityContext:
            {{- toYaml .Values.backend.securityContext | nindent 12 }}
          image: "{{ $image }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: wsgi
              containerPort: {{ .Values.backend.service.wsgi.port }}
              protocol: TCP
            - name: stats
              containerPort: {{ .Values.backend.service.stats.port }}
              protocol: TCP
          args: ["uwsgi", "--ini", "/var/run/p3m/uwsgi.ini"]
          envFrom:
            - configMapRef:
                name: {{ include "p3m.fullname" . }}-env
          volumeMounts:
            - name: p3m-statics
              mountPath: {{ .Values.config.static.localPath }}
            - name: p3m-secrets
              mountPath: /run/secrets/p3m
              readOnly: true
            - name: uwsgi-conf
              mountPath: /var/run/p3m
          livenessProbe:
            tcpSocket:
              port: uwsgi
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
