apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "p3m.fullname" . }}-uwsgi
data:
  uwsgi.ini: |-
    [uwsgi]
    socket = 0.0.0.0:{{ .Values.backend.service.wsgi.port }}
    pidfile = /tmp/p3m.pid
    
    enable-threads = true 
    ; processes = {{ .Values.config.uwsgi.numProcesses | default 1 }}
    ; threads = {{ .Values.config.uwsgi.numThreads | default 4 }} 

    chdir = /usr/src/app/
    module = p3m_project.wsgi:application

    stats = 0.0.0.0:{{ .Values.backend.service.stats.port }}
    stats-http = true

    strict = true
    master = true
    vacuum = true                        ; Delete sockets during shutdown
    single-interpreter = true
    die-on-term = true                   ; Shutdown when receiving SIGTERM (default is respawn)
    need-app = true
    thunder-lock = true

    touch-reload = /usr/src/app/p3m_project/wsgi.py
    buffer-size = 32768

    harakiri = 60                        ; forcefully kill workers after 60 seconds
    # py-callos-afterfork = true           ; allow workers to trap signals

    max-requests = 1000                  ; Restart workers after this many requests
    max-worker-lifetime = 3600           ; Restart workers after this many seconds
    reload-on-rss = 2048                 ; Restart workers after this much resident memory
    worker-reload-mercy = 60           
    cheaper-busyness-multiplier = 30     ; How many cycles to wait before killing workers
    cheaper-busyness-min = 20            ; Below this threshold, kill workers (if stable for multiplier cycles)
    cheaper-busyness-max = 70            ; Above this threshold, spawn new workers
    cheaper-busyness-backlog-alert = 16  ; Spawn emergency workers if more than this many requests are waiting in the queue    
    cheaper-busyness-backlog-step = 2    ; How many emergency workers to create if there are too many requests

immutable: false
